name: Approve Command Dispatch

on:
  repository_dispatch:
    types: [ approve-command ]

jobs:
  approve-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2.4.2

      - name: Issue Template Parser
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3.0.1
        with:
          issue-body: ${{ github.event.client_payload.github.payload.issue.body }}
          template-path: .github/ISSUE_TEMPLATE/model_request.yml

      - run: echo "$ISSUE_CONTEXT"
        env:
          ISSUE_CONTEXT: ${{ steps.issue-parser.outputs.jsonString }}
